apiVersion: v1
kind: Pod
metadata: 
  namespace: ui
  name: loginform
  labels:
    app: loginform
spec:
  containers:
  - name: loginform
    image: image_version
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: ui
  name: loginform-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 18
    targetPort: 80
    nodePort: 32765
  selector:
    app: loginform
