apiVersion: v1
kind: ReplicationController  # ReplicationController config starts
metadata:
  namespace: dev-test
  name: bmp-login-form
  labels:
    app: bmp-login-form
    version: latest
spec:
  replicas: 1
  selector:
    app: bmp-login-form
    version: latest
  template:  # pod config starts
    metadata:
      name: bmp-login-form
      labels:
        app: bmp-login-form
        version: latest
    spec:
      containers:
      - image: mohammadaszadali/image-version
        name: bmp-login-form
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  namespace: dev-test
  name: bmp-login-form-svc
  labels:
    app: bmp-login-form
    version: latest
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: bmp-login-form
    version: latest
